name: Deploy Egg.js app

on:
  push:
    branches:
      - main  # 监听 main 分支，你也可以根据实际情况更改为其他分支名

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies and build
      run: |
        npm install

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: 47.98.226.220
        username: root
        key: ${{ secrets.CENTOS }}
        script: |
          cd /root/cosmos-management
          git pull origin main
          cd /root/cosmos-management/client
          npm install
          npm run build
          cd /root/cosmos-management/lib/plugins/egg-generator
          npm install
          cd /root/cosmos-management
          npm install
          npm stop
          npm start
